# Generated by Django 4.0.3 on 2022-03-31 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_consumer_distributor_tax_alter_consumer_consumption'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumidor', models.CharField(max_length=50)),
                ('consumption', models.CharField(max_length=70)),
                ('coverage', models.FloatField()),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='consumer',
            name='discount_rules_key',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.discountrules'),
            preserve_default=False,
        ),
    ]
