# Generated by Django 4.0.3 on 2022-03-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_discountrules_consumer_discount_rules_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountrules',
            old_name='consumption',
            new_name='consumo',
        ),
        migrations.AlterField(
            model_name='discountrules',
            name='discount',
            field=models.FloatField(blank=True),
        ),
    ]
